The Nautilus DevOps team is working to deploy one of the applications on App Server 1 in Stratos DC. Due to a misconfiguration in the docker compose file, the deployment is failing. We would like you to take a look into it to identify and fix the issues. More details can be found below:
a. docker-compose.yml file is present on App Server 1 under /opt/docker directory.
b. Try to run the same and make sure it works fine.
c. Please do not change the container names being used. Also, do not update or alter any other valid config settings in the compose file or any other relevant data that can cause app failure.
Note: Please note that once you click on FINISH button all existing running/stopped containers will be destroyed, and your compose will be run.

Inside docker file there are couple of errors

sudo vi docker-compose.yml

``
version: '2'               ----> this needs to be changed to '3.3'
service:                   ---->this needs to be changed to services
    web:
        build: .
        container_name: python
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:         ----> in different version of tasks there is depends without _on
            - redis
    redis:
        from: redis         ----> this needs to be changed to image: redis / from not supported out there
        container_name: redis
      
  ``     
  Then save via escape  --> qw!
  
  run
  
  sudo docker-compose up and wait up for result.
  
  
