##this task is to create pod which will just put output via usage of env variables global in linux pod
## create yml file 
sudo vi file.yml
## input text bellow / bear in mind that 
## env are located in container section 
## also after pod deployment you may notice it's in crassh loopback but do not worry about it it's due inproper image used out here.
## metadata and labels are just for information purposes



apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
  labels:
    name: print-envars-greeting
spec:
  containers:
    - name: print-env-container
      image: bash
      env:
        - name: GREETING
          value: "Welcome to"
        - name: COMPANY
          value: "xFusionCorp"
        - name: GROUP
          value: "Ltd"
      command: ["echo"]
      args: ["$(GREETING) $(COMPANY) $(GROUP)"]
