## node js application 
## deploy as yml file kubectl create -f nameoffile.yml -n node-namespace-nautilus

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-datacenter
  namespace: node-namespace-datacenter
  labels:
    app: node-container-datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-container-datacenter
  template:
    metadata:
      labels:
        app: node-container-datacenter 
    spec:
      containers:
      - name: node-container-datacenter
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort: 80


## service 
## kubectl create -f nameoffile.yml -n node-namespace-nautilus

apiVersion: v1
kind: Service
metadata:
  name: node-service-datacenter
  namespace: node-namespace-datacenter
spec:
  selector:
    app: node-container-datacenter 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30012
