# Step 1: kubectl create namespace iron-namespace-nautilus
``
kubectl create namespace iron-namespace-nautilus
``
# Step 2: kubectl create -f someexamplename
# Step 3: Wait for the pods to be in 'Running' state. Note down any
#         frontend pod's name i.e. iron-gallery-deployment-nautilus-xxxxx
# Step 4: Verify: kubectl exec iron-gallery-deployment-nautilus-xxxxx -- curl http://localhost/
#         You should see a valid HTML content being returned
# Step 5: Verify: Open Irongallery app on browser by clicking 'Open Port on Host 1'
#         and port as NodePort below. You should see Irongallery app without any errors
# this app would start some front end which you could connect to later on. This deployment builds up

-Db in pod / docker container
-docker file share 
-service node port via nodeport acces for pod and DB
on sharing folder 

## start of yml deployment file
apiVersion: v1
kind: Service
metadata:
  name: iron-db-service-nautilus
  namespace: iron-namespace-nautilus
spec:
  type: ClusterIP
  selector:
    db: mariadb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: iron-gallery-service-nautilus
  namespace: iron-namespace-nautilus
spec:
  type: NodePort
  selector:
    run: iron-gallery
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-db-deployment-nautilus
  namespace: iron-namespace-nautilus
  labels:
    db: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      volumes:
        - name: db
          emptyDir: {}
      containers:
        - name: iron-db-container-nautilus
          image: kodekloud/irondb:2.0
          env:
            - name: MYSQL_DATABASE
              value: database_host
            - name: MYSQL_ROOT_PASSWORD
              value: P@55w.rd
            - name: MYSQL_PASSWORD
              value: P@55w.rd
            - name: MYSQL_USER
              value: kodekloud
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-gallery-deployment-nautilus
  namespace: iron-namespace-nautilus
  labels:
    run: iron-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: images
          emptyDir: {}
      containers:
        - name: iron-gallery-container-nautilus
          image: kodekloud/irongallery:2.0
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/data
            - name: images
              mountPath: /usr/share/nginx/html/uploads
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
